version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: ["node", "server.js"]
